### ISSUE TITLE
Breaks ox lib when no invoices

### ISSUE THREAD

**Issue by IgnornceIsBliss** [GouveiaXS/angelicxs_billing#1]
Replace the querey with this 

        MySQL.query('SELECT * FROM angelicxs_billing WHERE identifier = ?', {xPlayer.identifier}, function(result)
            if result then
                local var = tonumber(#result)
                if var >= 1 then
                    cb(result)
                end
            end
        end)
        
Otherwise you have to restart server as it breaks ox lib it's under the server section for invoice lookups

**Comment by GouveiaXS** [comment]
pulled.
